# Generated by Django 5.2.8 on 2025-11-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_address', models.CharField(max_length=255)),
                ('clinic_phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=150)),
                ('telegram', models.CharField(max_length=150)),
                ('whatsapp', models.CharField(max_length=150)),
                ('website', models.CharField(max_length=150)),
                ('location_lat', models.FloatField()),
                ('location_lng', models.FloatField()),
                ('footer_text', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
    ]
