# Generated by Django 5.2.8 on 2025-11-21 16:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('biography', models.TextField()),
                ('medical_registry_number', models.CharField(max_length=100)),
                ('experience_years', models.PositiveSmallIntegerField()),
                ('profile_image', models.ImageField(upload_to=core.models.doctor_profile_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=255)),
                ('clinic_address', models.CharField(max_length=255)),
                ('clinic_phone', models.CharField(max_length=50)),
                ('hospital_name', models.CharField(max_length=150)),
                ('hospital_address', models.CharField(max_length=255)),
                ('hospital_phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=150)),
                ('telegram', models.CharField(max_length=150)),
                ('whatsapp', models.CharField(max_length=150)),
                ('website', models.CharField(max_length=150)),
                ('location_lat', models.FloatField()),
                ('location_lng', models.FloatField()),
                ('footer_text', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
    ]
