# Generated by Django 5.2.8 on 2025-11-19 15:15

import doctor_info.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('biography', models.TextField()),
                ('medical_registry_number', models.CharField(max_length=100)),
                ('experience_years', models.PositiveSmallIntegerField()),
                ('clinic_address', models.TextField()),
                ('clinic_phone', models.CharField(max_length=50)),
                ('hospital_name', models.CharField(max_length=150)),
                ('profile_image', models.ImageField(upload_to=doctor_info.models.doctor_profile_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
